version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tokio
    versions:
    - 1.2.0
    - 1.3.0
    - 1.5.0
  - dependency-name: reqwest
    versions:
    - 0.11.2
    - 0.11.3
  - dependency-name: serde_derive
    versions:
    - 1.0.124
    - 1.0.125
  - dependency-name: serde
    versions:
    - 1.0.124
    - 1.0.125
  - dependency-name: hyper
    versions:
    - 0.14.4
  - dependency-name: serde_json
    versions:
    - 1.0.62
