on: [push, workflow_dispatch]

name: Continuous integration

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  build-packages:
    needs: [check, fmt, clippy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - el8
          # - el8:linux/arm64/v8
          - debian
          - debian_rpi3
        include:
          - package: el8
            artifact_name: el8
            artifact_glob: packages/build/el8/release/rpmbuild/RPMS/x86_64/ragent-*.rpm
            cloudsmith-distro: el
            cloudsmith-version: 8
            cloudsmith-format: rpm
          # - package: el8:linux/arm64/v8
          #   artifact_name: el8_rpi4
          #   artifact_glob: packages/build/el8/release/rpmbuild/RPMS/aarch64/ragent-*.rpm
          #   cloudsmith-distro: el
          #   cloudsmith-version: 8
          #   cloudsmith-format: rpm
          - package: debian
            artifact_name: debian
            artifact_glob: packages/build/debian/debian/ragent_*.deb
            cloudsmith-distro: any-distro
            cloudsmith-version: any-version
            cloudsmith-format: deb
          - package: debian_rpi3
            artifact_name: debian_rpi3
            artifact_glob: packages/build/debian_rpi3/armv7-unknown-linux-gnueabihf/debian/ragent_*.deb
            cloudsmith-distro: any-distro
            cloudsmith-version: any-version
            cloudsmith-format: deb
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install -y qemu-user-static
      - run: cd packages/ ; ./build_package ${{ matrix.package }}
      - run: |
            echo artifact=$(ls ${{ matrix.artifact_glob }}) >> $GITHUB_ENV
            echo cargo_version=$(cargo read-manifest | jq .version -r) >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ env.artifact }}
      - name: upload to cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: ${{ matrix.cloudsmith-format }}
          owner: 'ragent'
          repo: 'ragent'
          distro: ${{ matrix.cloudsmith-distro }}
          release: ${{ matrix.cloudsmith-version }}
          republish: 'true'
          file: ${{ env.artifact }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
