on: [push]

name: Continuous integration

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  build-packages:
    needs: [check, fmt, clippy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - centos7
          - centos8
          - debian_stretch
          - debian_stretch_rpi3
        include:
          - package: centos7
            artifact_glob: packages/build/centos7/release/rpmbuild/RPMS/x86_64/ragent-*.rpm
            cloudsmith-distro: el
            cloudsmith-version: 7
            cloudsmith-format: rpm
          - package: centos8
            artifact_glob: packages/build/centos8/release/rpmbuild/RPMS/x86_64/ragent-*.rpm
            cloudsmith-distro: el
            cloudsmith-version: 8
            cloudsmith-format: rpm
          - package: debian_stretch
            artifact_glob: packages/build/debian_stretch/debian/ragent_*.deb
            cloudsmith-distro: any-distro
            cloudsmith-version: any-version
            cloudsmith-format: deb
          - package: debian_stretch_rpi3
            artifact_glob: packages/build/debian_stretch_rpi3/armv7-unknown-linux-gnueabihf/debian/ragent_*.deb
            cloudsmith-distro: any-distro
            cloudsmith-version: any-version
            cloudsmith-format: deb
    steps:
      - uses: actions/checkout@v2
      - run: cd packages/ ; ./build_package ${{ matrix.package }}
      - run: |
            echo artifact=$(ls ${{ matrix.artifact_glob }}) >> $GITHUB_ENV
            echo cargo_version=$(cargo read-manifest | jq .version -r) >> $GITHUB_ENV
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.package }}
          path: ${{ env.artifact }}
      - name: upload to cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: ${{ matrix.cloudsmith-format }}
          owner: 'ragent'
          repo: 'ragent'
          distro: ${{ matrix.cloudsmith-distro }}
          release: ${{ matrix.cloudsmith-version }}
          republish: 'true'
          file: ${{ env.artifact }}
        if: ${{ !contains(env.cargo_version, 'alpha') && github.ref == 'refs/heads/master' }}
